"""TigerForm — Streamlit front-end.

Upload a swing video and get an annotated overlay, a similarity score vs. Tiger
Woods, a deviation breakdown, and coaching feedback.

Run with:  streamlit run app/streamlit_app.py
"""
import pathlib
import sys
import tempfile
import hashlib

# Make the src/ package importable when run via `streamlit run`.
_SRC = pathlib.Path(__file__).resolve().parents[1] / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

import numpy as np
import streamlit as st

from tigerform import config
from tigerform.model import TigerDiscriminator
from tigerform.reference import ReferenceTemplate
from tigerform.scorecard import build_scorecard
from tigerform.viz import deviation_chart

st.set_page_config(page_title="TigerForm", page_icon="⛳", layout="wide")


# --------------------------------------------------------------------------- #
# Artifact loading / building
# --------------------------------------------------------------------------- #
@st.cache_resource
def load_reference():
    return ReferenceTemplate.load()


@st.cache_resource
def load_discriminator():
    return TigerDiscriminator.load() if config.DISCRIMINATOR_PATH.exists() else None


def artifacts_ready() -> bool:
    return config.REFERENCE_TEMPLATE_PATH.exists()


def build_synthetic_artifacts():
    """Build a synthetic reference + discriminator on the fly (demo bootstrap)."""
    from tigerform.analyze import analyze_sequence
    from tigerform.reference import build_reference
    from tigerform.model import train_discriminator
    from tigerform.synthetic import make_dataset, reference_swings

    tiger_feats = [analyze_sequence(seq).features for seq in reference_swings(25)]
    build_reference(tiger_feats).save()

    dataset = make_dataset(n_tiger=25, n_amateur=30)
    feats = [analyze_sequence(seq).features for seq, _ in dataset]
    labels = [y for _, y in dataset]
    disc, metrics = train_discriminator(feats, labels)
    disc.save()
    return metrics


# --------------------------------------------------------------------------- #
# Rendering a result
# --------------------------------------------------------------------------- #
def show_result(result, features, reference, overlay_path=None):
    c = result.comparison
    left, right = st.columns([1, 1])

    with left:
        st.metric("Position Match", f"{c.position_match:.0f}/100",
                  help="How close your body angles and posture are to Tiger's at "
                       "address, top, and impact (static positions). Measured as "
                       "distance from the Tiger reference, so read it as relative.")
        if np.isfinite(c.tempo_match):
            st.metric("Tempo Match", f"{c.tempo_match:.0f}/100",
                      help="How close your rhythm — the backswing-to-downswing "
                           "ratio (~3:1 for Tiger) — is to Tiger's. A separate axis "
                           "from your positions: you can match one and not the other.")
        if overlay_path and pathlib.Path(overlay_path).exists():
            st.video(str(overlay_path))

    with right:
        st.subheader(result.feedback.headline)
        st.write(result.feedback.coaching_text)
        st.caption(f"Feedback generated by: {result.feedback.generated_by}")

    st.divider()
    st.pyplot(deviation_chart(c))
    st.caption("How far each position is from Tiger, in standard deviations. "
               "Right = you do more than Tiger, left = less; red = big difference, "
               "orange = moderate. The scorecard below has the details and fixes.")

    st.subheader("Swing scorecard")
    st.caption("Each key position vs Tiger's, what it means, and what to do.  "
               "✅ in Tiger's range · ⚠️ slightly off · ❌ work on it.")
    _ICON = {"good": "✅", "minor": "⚠️", "off": "❌"}
    for it in build_scorecard(features, reference):
        with st.container(border=True):
            head, nums = st.columns([3, 1])
            head.markdown(f"**{_ICON[it.status]} {it.title}**")
            head.caption(it.description)
            nums.markdown(f"**You:** {it.your_value}  \n**Tiger:** {it.tiger_value}")
            if it.status != "good":
                head.markdown(f"→ *{it.instruction}*")

    report_json = _report_json(result)
    report_key = hashlib.sha256(report_json.encode("utf-8")).hexdigest()[:12]
    st.download_button("Download JSON report",
                       data=report_json, file_name="tigerform_report.json",
                       mime="application/json", key=f"download-report-{report_key}")


def _report_json(result) -> str:
    import json
    return json.dumps(result.report(), indent=2)


# --------------------------------------------------------------------------- #
# UI
# --------------------------------------------------------------------------- #
st.title("⛳ TigerForm")
st.caption("Compare your golf swing mechanics to Tiger Woods' and get coaching feedback.")

_ROTATION_OPTIONS = {
    "Auto (from video)": "auto", "No rotation": 0,
    "Rotate 90° ↻": 90, "Rotate 180°": 180, "Rotate 90° ↺": 270,
}

with st.sidebar:
    st.header("Settings")
    handedness = st.radio("Handedness", ["right", "left"], horizontal=True)
    st.selectbox("Club (context only)", ["Driver", "Iron", "Wedge"])
    rotation_label = st.selectbox(
        "Video rotation", list(_ROTATION_OPTIONS),
        help="'Auto' uses the clip's metadata. If your video shows up "
             "sideways or upside-down, pick a manual rotation.")
    rotate = _ROTATION_OPTIONS[rotation_label]
    st.divider()
    st.markdown("**Tip:** film front-on or down-the-line, full swing in frame.")

if not artifacts_ready():
    st.warning("No Tiger reference template found yet.")
    st.write("Build a synthetic reference + discriminator to try the app, or run "
             "`python scripts/build_reference.py` and "
             "`python scripts/train_discriminator.py`.")
    if st.button("Build synthetic demo artifacts"):
        with st.spinner("Generating synthetic swings and training..."):
            metrics = build_synthetic_artifacts()
        st.success("Artifacts built.")
        st.json(metrics)
        st.cache_resource.clear()
        st.rerun()
    st.stop()

reference = load_reference()
discriminator = load_discriminator()

st.subheader("Analyze a swing video")
up = st.file_uploader("Upload a swing video", type=["mp4", "mov", "m4v", "avi"])
if up is not None:
    suffix = pathlib.Path(up.name).suffix
    with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
        tmp.write(up.read())
        tmp_path = tmp.name
    with st.spinner("Estimating pose and analyzing swing..."):
        from tigerform.pipeline import run_pipeline
        result = run_pipeline(tmp_path, handedness=handedness,
                              use_claude=True, render=True,
                              out_dir=config.ARTIFACTS_DIR / "upload",
                              reference=reference, discriminator=discriminator,
                              rotate=rotate)
    for w in result.warnings:
        st.info(w)
    show_result(result, result.features, reference, result.overlay_path)
