"""TigerForm — Streamlit front-end.

Upload a swing video (or run a synthetic demo) and get an annotated overlay, a
similarity score vs. Tiger Woods, a deviation breakdown, and coaching feedback.

Run with:  streamlit run app/streamlit_app.py
"""
import pathlib
import sys
import tempfile

# Make the src/ package importable when run via `streamlit run`.
_SRC = pathlib.Path(__file__).resolve().parents[1] / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

import numpy as np
import streamlit as st

from tigerform import config
from tigerform.ingest import from_frames
from tigerform.model import TigerDiscriminator
from tigerform.reference import ReferenceTemplate
from tigerform.synthetic import TIGER, AMATEUR, synthetic_pose
from tigerform.viz import deviation_chart, series_chart

st.set_page_config(page_title="TigerForm", page_icon="⛳", layout="wide")


# --------------------------------------------------------------------------- #
# Artifact loading / building
# --------------------------------------------------------------------------- #
@st.cache_resource
def load_reference():
    return ReferenceTemplate.load()


@st.cache_resource
def load_discriminator():
    return TigerDiscriminator.load() if config.DISCRIMINATOR_PATH.exists() else None


def artifacts_ready() -> bool:
    return config.REFERENCE_TEMPLATE_PATH.exists()


def build_synthetic_artifacts():
    """Build a synthetic reference + discriminator on the fly (demo bootstrap)."""
    from tigerform.analyze import analyze_sequence
    from tigerform.reference import build_reference
    from tigerform.model import train_discriminator
    from tigerform.synthetic import make_dataset
    from dataclasses import replace

    rng = np.random.default_rng(7)
    tiger_feats = [analyze_sequence(synthetic_pose(
        replace(TIGER, n_frames=int(rng.integers(85, 105))), seed=500 + i)).features
        for i in range(25)]
    build_reference(tiger_feats).save()

    dataset = make_dataset(n_tiger=25, n_amateur=30)
    feats = [analyze_sequence(seq).features for seq, _ in dataset]
    labels = [y for _, y in dataset]
    disc, metrics = train_discriminator(feats, labels)
    disc.save()
    return metrics


# --------------------------------------------------------------------------- #
# Rendering a result
# --------------------------------------------------------------------------- #
def show_result(result, features, reference, overlay_path=None):
    c = result.comparison
    left, right = st.columns([1, 1])

    with left:
        st.metric("Similarity to Tiger", f"{c.similarity_score:.0f}/100")
        if c.tiger_likeness is not None:
            st.metric("Tiger-likeness (discriminator)", f"{c.tiger_likeness:.2f}")
        if np.isfinite(c.sequence_similarity):
            st.metric("Swing-sequence similarity (DTW)", f"{c.sequence_similarity:.0f}/100")
        if overlay_path and pathlib.Path(overlay_path).exists():
            st.video(str(overlay_path))

    with right:
        st.subheader(result.feedback.headline)
        st.write(result.feedback.coaching_text)
        st.caption(f"Feedback generated by: {result.feedback.generated_by}")

    st.divider()
    cc1, cc2 = st.columns([1, 1])
    with cc1:
        st.pyplot(deviation_chart(c))
    with cc2:
        st.pyplot(series_chart(features, reference))

    if result.feedback.tips:
        st.subheader("Prioritized fixes")
        for t in result.feedback.tips:
            with st.expander(t.title):
                st.write(t.message)
                st.caption(t.detail)
                if t.drill:
                    st.markdown(f"**Drill:** {t.drill}")

    st.download_button("Download JSON report",
                       data=_report_json(result), file_name="tigerform_report.json",
                       mime="application/json")


def _report_json(result) -> str:
    import json
    return json.dumps(result.report(), indent=2)


# --------------------------------------------------------------------------- #
# UI
# --------------------------------------------------------------------------- #
st.title("⛳ TigerForm")
st.caption("Compare your golf swing mechanics to Tiger Woods' and get coaching feedback.")

with st.sidebar:
    st.header("Settings")
    handedness = st.radio("Handedness", ["right", "left"], horizontal=True)
    st.selectbox("Club (context only)", ["Driver", "Iron", "Wedge"])
    use_claude = st.toggle("Claude-phrased feedback", value=True,
                           help="Requires ANTHROPIC_API_KEY; falls back to "
                                "template coaching if unavailable.")
    st.divider()
    st.markdown("**Tip:** film front-on or down-the-line, full swing in frame.")

if not artifacts_ready():
    st.warning("No Tiger reference template found yet.")
    st.write("Build a synthetic reference + discriminator to try the app, or run "
             "`python scripts/build_reference.py` and "
             "`python scripts/train_discriminator.py`.")
    if st.button("Build synthetic demo artifacts"):
        with st.spinner("Generating synthetic swings and training..."):
            metrics = build_synthetic_artifacts()
        st.success("Artifacts built.")
        st.json(metrics)
        st.cache_resource.clear()
        st.rerun()
    st.stop()

reference = load_reference()
discriminator = load_discriminator()

tab_upload, tab_demo = st.tabs(["Analyze a video", "Synthetic demo"])

with tab_upload:
    up = st.file_uploader("Upload a swing video", type=["mp4", "mov", "m4v", "avi"])
    if up is not None:
        suffix = pathlib.Path(up.name).suffix
        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
            tmp.write(up.read())
            tmp_path = tmp.name
        with st.spinner("Estimating pose and analyzing swing..."):
            from tigerform.pipeline import run_pipeline
            result = run_pipeline(tmp_path, handedness=handedness,
                                  use_claude=use_claude, render=True,
                                  out_dir=config.ARTIFACTS_DIR / "upload",
                                  reference=reference, discriminator=discriminator)
        for w in result.warnings:
            st.info(w)
        show_result(result, result.features, reference, result.overlay_path)

with tab_demo:
    st.write("No video handy? Analyze a synthetic swing to see the full pipeline.")
    kind = st.radio("Synthetic swing type", ["amateur-like", "tiger-like"],
                    horizontal=True)
    if st.button("Run synthetic analysis"):
        params = TIGER if kind == "tiger-like" else AMATEUR
        seq = synthetic_pose(params, seed=123)
        seq.handedness = handedness
        frames = [np.full((960, 540, 3), 30, np.uint8) for _ in range(seq.n_frames)]
        seq.width, seq.height = 540, 960
        video = from_frames(frames, fps=seq.fps)
        with st.spinner("Analyzing synthetic swing..."):
            from tigerform.pipeline import run_on_sequence
            result = run_on_sequence(seq, video=video, use_claude=use_claude,
                                     render=True,
                                     out_dir=config.ARTIFACTS_DIR / "demo",
                                     reference=reference, discriminator=discriminator)
        show_result(result, result.features, reference, result.overlay_path)
